/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba.pkg2;


import java.util.ArrayList;
import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Interfaz extends javax.swing.JFrame {

    
    /**
     * Creates new form Interfaz
     */
    
    ArrayList<Persona> lista = new ArrayList<>();
    
    public Interfaz() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TiempoSeleccion = new javax.swing.JTextField();
        TiempoMergeSort = new javax.swing.JTextField();
        ArregloAleatorio1 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPersonas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        IngresarNombre = new javax.swing.JTextField();
        AgregarDatos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BotonReemplazar = new javax.swing.JButton();
        IngresarEdad = new javax.swing.JTextField();
        ResultadoCaracteres = new javax.swing.JTextField();
        CantidadArreglo2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CrearArreglo = new javax.swing.JButton();
        IngresarCedula = new javax.swing.JTextField();
        BotonBurbuja = new javax.swing.JButton();
        BotonInsercion = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BotonSeleccion = new javax.swing.JButton();
        BotonMergeSort = new javax.swing.JButton();
        ArregloOrdenado = new javax.swing.JTextField();
        ArregloAleatorio2 = new javax.swing.JTextField();
        CantidadArreglo1 = new javax.swing.JTextField();
        DatosOrdenados1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Media = new javax.swing.JButton();
        Varianza = new javax.swing.JButton();
        Desviacion = new javax.swing.JButton();
        ResultadoEstadistica = new javax.swing.JTextField();
        IngresarCaracteres = new javax.swing.JTextField();
        CedulaBurbuja = new javax.swing.JButton();
        EdadBurbuja = new javax.swing.JButton();
        TiempoBurbuja = new javax.swing.JTextField();
        TiempoInsercion = new javax.swing.JTextField();
        CedulaMergeSort = new javax.swing.JButton();
        EdadMergeSort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TiempoSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiempoSeleccionActionPerformed(evt);
            }
        });

        TiempoMergeSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiempoMergeSortActionPerformed(evt);
            }
        });

        ArregloAleatorio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArregloAleatorio1ActionPerformed(evt);
            }
        });

        jButton11.setText("Ordenar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        TablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Edad", "Cedula"
            }
        ));
        jScrollPane1.setViewportView(TablaPersonas);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingrese Nombre :");

        IngresarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarNombreActionPerformed(evt);
            }
        });

        AgregarDatos.setText("Agregar");
        AgregarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarDatosActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingrese Edad :");

        BotonReemplazar.setText("Reemplazar");
        BotonReemplazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReemplazarActionPerformed(evt);
            }
        });

        ResultadoCaracteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoCaracteresActionPerformed(evt);
            }
        });

        CantidadArreglo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadArreglo2ActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ingrese Cedula :");

        CrearArreglo.setText("Crear el Arreglo de Double");
        CrearArreglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearArregloActionPerformed(evt);
            }
        });

        BotonBurbuja.setText("Burbuja");
        BotonBurbuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBurbujaActionPerformed(evt);
            }
        });

        BotonInsercion.setText("Inserción");
        BotonInsercion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInsercionActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ordenar por :");

        BotonSeleccion.setText("Selección");
        BotonSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSeleccionActionPerformed(evt);
            }
        });

        BotonMergeSort.setText("MergeSort");
        BotonMergeSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMergeSortActionPerformed(evt);
            }
        });

        ArregloOrdenado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArregloOrdenadoActionPerformed(evt);
            }
        });

        ArregloAleatorio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArregloAleatorio2ActionPerformed(evt);
            }
        });

        CantidadArreglo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadArreglo1ActionPerformed(evt);
            }
        });

        DatosOrdenados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatosOrdenados1ActionPerformed(evt);
            }
        });

        jButton1.setText("Crear el Arreglo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Media.setText("Media");
        Media.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MediaActionPerformed(evt);
            }
        });

        Varianza.setText("Varianza");
        Varianza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VarianzaActionPerformed(evt);
            }
        });

        Desviacion.setText("D. Estandar");
        Desviacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesviacionActionPerformed(evt);
            }
        });

        ResultadoEstadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoEstadisticaActionPerformed(evt);
            }
        });

        IngresarCaracteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarCaracteresActionPerformed(evt);
            }
        });

        CedulaBurbuja.setText("Cedula y Burbuja");
        CedulaBurbuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaBurbujaActionPerformed(evt);
            }
        });

        EdadBurbuja.setText("Edad y Burbuja");
        EdadBurbuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadBurbujaActionPerformed(evt);
            }
        });

        TiempoBurbuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiempoBurbujaActionPerformed(evt);
            }
        });

        TiempoInsercion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiempoInsercionActionPerformed(evt);
            }
        });

        CedulaMergeSort.setText("Cedula y MergeSort");
        CedulaMergeSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaMergeSortActionPerformed(evt);
            }
        });

        EdadMergeSort.setText("Edad y MergeSort");
        EdadMergeSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadMergeSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ArregloAleatorio2)
                    .addComponent(ArregloAleatorio1)
                    .addComponent(ArregloOrdenado)
                    .addComponent(ResultadoCaracteres)
                    .addComponent(DatosOrdenados1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Media, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Varianza)
                        .addGap(18, 18, 18)
                        .addComponent(Desviacion)
                        .addGap(18, 18, 18)
                        .addComponent(ResultadoEstadistica))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IngresarCaracteres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonReemplazar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CantidadArreglo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CantidadArreglo2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CrearArreglo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TiempoBurbuja, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonBurbuja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonInsercion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TiempoInsercion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotonSeleccion, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(TiempoSeleccion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotonMergeSort, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(TiempoMergeSort)))
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IngresarNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IngresarEdad))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IngresarCedula))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CedulaBurbuja, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CedulaMergeSort, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EdadBurbuja, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EdadMergeSort, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AgregarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CantidadArreglo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ArregloAleatorio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DatosOrdenados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Media)
                    .addComponent(Varianza)
                    .addComponent(Desviacion)
                    .addComponent(ResultadoEstadistica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IngresarCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonReemplazar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResultadoCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CantidadArreglo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CrearArreglo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ArregloAleatorio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonBurbuja)
                    .addComponent(BotonMergeSort)
                    .addComponent(BotonSeleccion)
                    .addComponent(BotonInsercion))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TiempoBurbuja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TiempoInsercion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TiempoSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TiempoMergeSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ArregloOrdenado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AgregarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IngresarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IngresarEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IngresarCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CedulaBurbuja)
                                    .addComponent(EdadBurbuja))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CedulaMergeSort)
                                    .addComponent(EdadMergeSort)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TiempoSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiempoSeleccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TiempoSeleccionActionPerformed

    private void TiempoMergeSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiempoMergeSortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TiempoMergeSortActionPerformed

    private void ArregloAleatorio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArregloAleatorio1ActionPerformed

    }//GEN-LAST:event_ArregloAleatorio1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        String pantalla = ArregloAleatorio1.getText();
        CalculosEstadisticos orden = new CalculosEstadisticos();
        DatosOrdenados1.setText(orden.orden(pantalla));
    }//GEN-LAST:event_jButton11ActionPerformed

    private void IngresarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarNombreActionPerformed

   
    private void AgregarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarDatosActionPerformed

        Persona persona = new Persona (IngresarNombre.getText(),IngresarEdad.getText(),IngresarCedula.getText());
        lista.add(persona);
        
        mostrar();
        IngresarNombre.setText("");
        IngresarEdad.setText("");
        IngresarCedula.setText("");
    }//GEN-LAST:event_AgregarDatosActionPerformed

    public void mostrar()
    {
        String matriz[][] = new String [lista.size()][3];
        for(int i=0; i<lista.size();i++)
        {
            matriz[i][0]=lista.get(i).getNombre();
            matriz[i][1]=lista.get(i).getEdad();
            matriz[i][2]=lista.get(i).getCedula();
        }
        TablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "Nombre", "Edad", "Cedula"
            }
        ));
    }
    private void BotonReemplazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReemplazarActionPerformed
        String pantalla = IngresarCaracteres.getText();
        LineaCaracteres letra = new LineaCaracteres();
        ResultadoCaracteres.setText(letra.Reemplazar(pantalla));
    }//GEN-LAST:event_BotonReemplazarActionPerformed

    private void ResultadoCaracteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoCaracteresActionPerformed

    }//GEN-LAST:event_ResultadoCaracteresActionPerformed

    private void CantidadArreglo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadArreglo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadArreglo2ActionPerformed

    private void CrearArregloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearArregloActionPerformed
        String cantidad = CantidadArreglo2.getText();
        String pantalla="";
        double []numero = new double [Integer.valueOf(cantidad)];
        String []llenar = new String[Integer.valueOf(cantidad)];
        
        for(int i=0;i<Integer.valueOf(cantidad);i++)
        {
            Random rnd = new Random();
            numero[i] = rnd.nextDouble()*100;
            llenar[i] = String.valueOf(numero[i]);
        }
        for(int i=0;i<Integer.valueOf(cantidad);i++)
        {
            if(i==Integer.valueOf(cantidad)-1)
            {
                pantalla=pantalla+llenar[i];
            }
            else
            {
                pantalla=pantalla+llenar[i]+",";
            }
        }
        ArregloAleatorio2.setText(pantalla);
    }//GEN-LAST:event_CrearArregloActionPerformed

    private void BotonBurbujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBurbujaActionPerformed
        Ordenamiento orden = new Ordenamiento();
        long Tinicio,Tfinal,Tiempo;
        Tinicio = System.nanoTime();
        String pantalla = ArregloAleatorio2.getText();
        
        ArregloOrdenado.setText(orden.Burbuja(pantalla));
        Tfinal = System.nanoTime();
        Tiempo = Tfinal-Tinicio;
        TiempoBurbuja.setText(String.valueOf(Tiempo)+"milisegundos");
    }//GEN-LAST:event_BotonBurbujaActionPerformed

    private void BotonInsercionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInsercionActionPerformed
        Ordenamiento orden = new Ordenamiento();
        long Tinicio,Tfinal,Tiempo;
        Tinicio = System.nanoTime();
        String pantalla = ArregloAleatorio2.getText();
        
        ArregloOrdenado.setText(orden.Insercion(pantalla));
        Tfinal = System.nanoTime();
        Tiempo = Tfinal-Tinicio;
        TiempoInsercion.setText(String.valueOf(Tiempo)+"milisegundos");
    }//GEN-LAST:event_BotonInsercionActionPerformed

    private void BotonSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSeleccionActionPerformed
        Ordenamiento orden = new Ordenamiento();
        long Tinicio,Tfinal,Tiempo;
        Tinicio = System.nanoTime();
        String pantalla = ArregloAleatorio2.getText();
        
        ArregloOrdenado.setText(orden.Seleccion(pantalla));
        Tfinal = System.nanoTime();
        Tiempo = Tfinal-Tinicio;
        TiempoSeleccion.setText(String.valueOf(Tiempo)+"milisegundos");
        
    }//GEN-LAST:event_BotonSeleccionActionPerformed

    private void BotonMergeSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMergeSortActionPerformed
        Ordenamiento orden = new Ordenamiento();
        long Tinicio,Tfinal,Tiempo;
        Tinicio = System.nanoTime();
        String pantalla = ArregloAleatorio2.getText();
        
        ArregloOrdenado.setText(orden.OrganizarMerge(pantalla));
        Tfinal = System.nanoTime();
        Tiempo = Tfinal-Tinicio;
        TiempoMergeSort.setText(String.valueOf(Tiempo)+"milisegundos");
    }//GEN-LAST:event_BotonMergeSortActionPerformed

    private void ArregloOrdenadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArregloOrdenadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArregloOrdenadoActionPerformed

    private void ArregloAleatorio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArregloAleatorio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArregloAleatorio2ActionPerformed

    private void CantidadArreglo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadArreglo1ActionPerformed
        String numero = CantidadArreglo1.getText();

        CantidadArreglo1.setText(numero);
    }//GEN-LAST:event_CantidadArreglo1ActionPerformed

    private void DatosOrdenados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatosOrdenados1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatosOrdenados1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cantidad = CantidadArreglo1.getText();
        String pantalla="";
        int []numero = new int [Integer.valueOf(cantidad)];
        String []llenar = new String[Integer.valueOf(cantidad)];
        for(int i=0;i<Integer.valueOf(cantidad);i++)
        {
            numero[i] = (int) (Math.random()*100);
            llenar[i] = String.valueOf(numero[i]);
        }
        for(int i=0;i<Integer.valueOf(cantidad);i++)
        {
            if(i==Integer.valueOf(cantidad)-1)
            {
                pantalla=pantalla+llenar[i];
            }
            else
            {
                pantalla=pantalla+llenar[i]+",";
            }
        }
        ArregloAleatorio1.setText(pantalla);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MediaActionPerformed

        String pantalla = DatosOrdenados1.getText();
        CalculosEstadisticos calculos = new CalculosEstadisticos();
        ResultadoEstadistica.setText(calculos.Media(pantalla));

    }//GEN-LAST:event_MediaActionPerformed

    private void VarianzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VarianzaActionPerformed

        String pantalla = DatosOrdenados1.getText();
        CalculosEstadisticos calculos = new CalculosEstadisticos();
        ResultadoEstadistica.setText(calculos.Varianza(pantalla));

    }//GEN-LAST:event_VarianzaActionPerformed

    private void DesviacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesviacionActionPerformed
        String pantalla = DatosOrdenados1.getText();
        CalculosEstadisticos calculos = new CalculosEstadisticos();
        ResultadoEstadistica.setText(calculos.DesviacionEstandar(pantalla));
    }//GEN-LAST:event_DesviacionActionPerformed

    private void ResultadoEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoEstadisticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultadoEstadisticaActionPerformed

    private void IngresarCaracteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarCaracteresActionPerformed

    }//GEN-LAST:event_IngresarCaracteresActionPerformed

    private void CedulaBurbujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaBurbujaActionPerformed
        OrdenPersonas ordenamiento = new OrdenPersonas();
        int tamaño = lista.size();
        String matriz[][] = new String [lista.size()][3];
        for(int i=0; i<lista.size();i++)
        {
            matriz[i][0]=lista.get(i).getNombre();
            matriz[i][1]=lista.get(i).getEdad();
            matriz[i][2]=lista.get(i).getCedula();
        }
        
        TablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            ordenamiento.MetodoBurbujaCedula(matriz, tamaño),
            new String [] {
                "Nombre", "Edad", "Cedula"
            }
        ));
    }//GEN-LAST:event_CedulaBurbujaActionPerformed

    private void EdadBurbujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadBurbujaActionPerformed
        OrdenPersonas ordenamiento = new OrdenPersonas();
        String matriz[][] = new String [lista.size()][3];
        int tamaño =lista.size();
        for(int i=0; i<tamaño;i++)
        {
            matriz[i][0]=lista.get(i).getNombre();
            matriz[i][1]=lista.get(i).getEdad();
            matriz[i][2]=lista.get(i).getCedula();
        }
        
        TablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            ordenamiento.MetodoBurbujaEdad(matriz, tamaño),
            new String [] {
                "Nombre", "Edad", "Cedula"
            }
        ));
    }//GEN-LAST:event_EdadBurbujaActionPerformed

    private void TiempoBurbujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiempoBurbujaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TiempoBurbujaActionPerformed

    private void TiempoInsercionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiempoInsercionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TiempoInsercionActionPerformed

    private void CedulaMergeSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaMergeSortActionPerformed
        OrdenPersonas ordenamiento = new OrdenPersonas();
        String matriz[][] = new String [lista.size()][3];
        int tamaño = lista.size();
        for(int i=0; i<lista.size();i++)
        {
            matriz[i][0]=lista.get(i).getNombre();
            matriz[i][1]=lista.get(i).getEdad();
            matriz[i][2]=lista.get(i).getCedula();
        }
        TablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            ordenamiento.MetodoBurbujaCedula(matriz, tamaño),
            new String [] {
                "Nombre", "Edad", "Cedula"
            }
        ));
    }//GEN-LAST:event_CedulaMergeSortActionPerformed

    private void EdadMergeSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadMergeSortActionPerformed
        OrdenPersonas ordenamiento = new OrdenPersonas();
        String matriz[][] = new String [lista.size()][3];
        int tamaño =lista.size();
        for(int i=0; i<lista.size();i++)
        {
            matriz[i][0]=lista.get(i).getNombre();
            matriz[i][1]=lista.get(i).getEdad();
            matriz[i][2]=lista.get(i).getCedula();
        }
        TablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            ordenamiento.MetodoBurbujaEdad(matriz, tamaño),
            new String [] {
                "Nombre", "Edad", "Cedula"
            }
        ));
    }//GEN-LAST:event_EdadMergeSortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarDatos;
    private javax.swing.JTextField ArregloAleatorio1;
    private javax.swing.JTextField ArregloAleatorio2;
    private javax.swing.JTextField ArregloOrdenado;
    private javax.swing.JButton BotonBurbuja;
    private javax.swing.JButton BotonInsercion;
    private javax.swing.JButton BotonMergeSort;
    private javax.swing.JButton BotonReemplazar;
    private javax.swing.JButton BotonSeleccion;
    private javax.swing.JTextField CantidadArreglo1;
    private javax.swing.JTextField CantidadArreglo2;
    private javax.swing.JButton CedulaBurbuja;
    private javax.swing.JButton CedulaMergeSort;
    private javax.swing.JButton CrearArreglo;
    private javax.swing.JTextField DatosOrdenados1;
    private javax.swing.JButton Desviacion;
    private javax.swing.JButton EdadBurbuja;
    private javax.swing.JButton EdadMergeSort;
    private javax.swing.JTextField IngresarCaracteres;
    private javax.swing.JTextField IngresarCedula;
    private javax.swing.JTextField IngresarEdad;
    private javax.swing.JTextField IngresarNombre;
    private javax.swing.JButton Media;
    private javax.swing.JTextField ResultadoCaracteres;
    private javax.swing.JTextField ResultadoEstadistica;
    private javax.swing.JTable TablaPersonas;
    private javax.swing.JTextField TiempoBurbuja;
    private javax.swing.JTextField TiempoInsercion;
    private javax.swing.JTextField TiempoMergeSort;
    private javax.swing.JTextField TiempoSeleccion;
    private javax.swing.JButton Varianza;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
